# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inserisciPrenotazioneGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1356, 823)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1401, 831))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/testBackground/sfondo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(770, 20, 551, 651))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("QRadioButton\n"
"{\n"
"    border: 5px solid rgb(0, 85, 255);\n"
"    background-color: rgb(255, 0, 127);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QRadioButton:hover\n"
"{\n"
"    border: 5px solid rgb(255, 0, 255);\n"
"    background-color: rgb(255, 85, 0);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"\n"
"QRadioButton:focus\n"
"{\n"
"    border: 2px solid rgb(255, 239, 14);\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 2, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("QRadioButton\n"
"{\n"
"    border: 5px solid rgb(0, 85, 255);\n"
"    background-color: rgb(255, 0, 127);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QRadioButton:hover\n"
"{\n"
"    border: 5px solid rgb(255, 0, 255);\n"
"    background-color: rgb(255, 85, 0);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"\n"
"QRadioButton:focus\n"
"{\n"
"    border: 2px solid rgb(255, 239, 14);\n"
"}")
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"    border: 5px solid rgb(0, 85, 255);\n"
"    background-color: rgb(255, 0, 127);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QLabel:hover\n"
"{\n"
"    border: 5px solid rgb(255, 0, 255);\n"
"    background-color: rgb(255, 85, 0);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("QRadioButton\n"
"{\n"
"    border: 5px solid rgb(0, 85, 255);\n"
"    background-color: rgb(255, 0, 127);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QRadioButton:hover\n"
"{\n"
"    border: 5px solid rgb(255, 0, 255);\n"
"    background-color: rgb(255, 85, 0);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"\n"
"QRadioButton:focus\n"
"{\n"
"    border: 2px solid rgb(255, 239, 14);\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 3, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(570, 720, 321, 65))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    border: 5px solid rgb(0, 85, 255);\n"
"    background-color: rgb(255, 0, 127);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border: 5px solid rgb(255, 0, 255);\n"
"    background-color: rgb(255, 85, 0);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"\n"
"QLineEdit: pressed\n"
"{\n"
"    border: 5px solid rgb(255, 239, 14);\n"
"    background-color: rgb(255, 170, 0)\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(10, 20, 651, 651))
        self.listView.setStyleSheet("QListView\n"
"{\n"
"    border: 5px solid rgb(0, 85, 255);\n"
"    background-color: rgb(255, 0, 127);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QListView:hover\n"
"{\n"
"    border: 5px solid rgb(255, 0, 255);\n"
"    background-color: rgb(255, 85, 0);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"\n"
"QListView:focus\n"
"{\n"
"    border: 2px solid rgb(255, 239, 14);\n"
"}")
        self.listView.setObjectName("listView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Inserisci Prenotazione"))
        self.radioButton.setText(_translate("Form", "Sala Prove"))
        self.radioButton_3.setText(_translate("Form", "Mix e Master"))
        self.label_2.setText(_translate("Form", "Data"))
        self.radioButton_2.setText(_translate("Form", "Incisione"))
        self.pushButton.setText(_translate("Form", "SALVA"))
import testqrc_rc
