# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from Home.View.homeView import Ui_Form


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1296, 756)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, -30, 691, 361))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/login/logo.png"))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 300, 1211, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.loginButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton\n"
"{\n"
"    border: 5px solid rgb(0, 85, 255);\n"
"    background-color: rgb(255, 0, 127);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border: 5px solid rgb(255, 0, 255);\n"
"    background-color: rgb(255, 85, 0);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"\n"
"QLineEdit: pressed\n"
"{\n"
"    border: 5px solid rgb(255, 239, 14);\n"
"    background-color: rgb(255, 170, 0)\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.gridLayout.addWidget(self.loginButton, 8, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("QLineEdit{\n"
"    border: 5px solid rgb(0, 85, 255);\n"
"    background-color: rgb(255, 0, 127);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QLineEdit:hover\n"
"{\n"
"    border: 5px solid rgb(255, 0, 255);\n"
"    background-color: rgb(255, 85, 0);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"\n"
"QLineEdit: focus\n"
"{\n"
"    border: 2px solid rgb(255, 239, 14);\n"
"}")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 7, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.userLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.userLineEdit.setFont(font)
        self.userLineEdit.setStyleSheet("QLineEdit{\n"
"    border: 5px solid rgb(0, 85, 255);\n"
"    background-color: rgb(255, 0, 127);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"    color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QLineEdit:hover\n"
"{\n"
"    border: 5px solid rgb(255, 0, 255);\n"
"    background-color: rgb(255, 85, 0);\n"
"    padding-left: 30px;\n"
"    padding-right: 30px;\n"
"}\n"
"\n"
"QLineEdit: focus\n"
"{\n"
"    border: 2px solid rgb(255, 239, 14);\n"
"}")
        self.userLineEdit.setObjectName("userLineEdit")
        self.gridLayout.addWidget(self.userLineEdit, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1301, 761))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/login/sfondo.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.gridLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.loginButton.clicked.connect(self.access) #LINK DEL BUTTON LOGIN


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reheasal Room Booker"))
        self.loginButton.setText(_translate("MainWindow", "ACCEDI"))
        self.passwordLineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.userLineEdit.setPlaceholderText(_translate("MainWindow", "Nome Utente"))

    #Metodo che apre la finestra Home
    def access(self):
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.accessControl()
        self.Form.show()

    #Metodo che controlla i campi inseriti
    def accessControl(self):
        print(self.userLineEdit.text())
        print(self.passwordLineEdit.text())
        user = self.userLineEdit.text()
        pas = self.passwordLineEdit.text()
        #manca lettura file

        # QMessageBox.critical(self, 'Accesso Negato', 'Le credenziali inserite sono errate', QMessageBox.Ok,
        #                      QMessageBox.Ok)
import Login.View.login_rc


