# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from ListaClienti.View.listaClientiView import ListaClientiUi_Form
from ListaDipendenti.View.listaDipendentiView import ListaDipendentiUi_Form
from Impostazioni.View.impostazioniView import ImpostazioniUi_Form


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1425, 896)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        Form.setFont(font)
        Form.setStyleSheet("\n"
"QLineEdit{\n"
"border: 5px solid rgb(0, 85, 255);\n"
"background-color: rgb(255, 0, 127);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QLineEdit:hover\n"
"{\n"
"border: 5px solid rgb(255, 0, 255);\n"
"background-color: rgb(255, 85, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"\n"
"QLineEdit: focus\n"
"{\n"
"border: 2px solid rgb(255, 239, 14);\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"border: 5px solid rgb(0, 85, 255);\n"
"background-color: rgb(255, 0, 127);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QPushButton: hover\n"
"{\n"
"border: 5px solid rgb(255, 0, 255);\n"
"background-color: rgb(255, 85, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"\n"
"QLineEdit: pressed\n"
"{\n"
"border: 5px solid rgb(255, 239, 14);\n"
"background-color: rgb(255, 170, 0)\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"\n"
"")
        self.backgroundLabel = QtWidgets.QLabel(Form)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 1431, 901))
        self.backgroundLabel.setText("")
        self.backgroundLabel.setPixmap(QtGui.QPixmap(":/home/sfondo.jpg"))
        self.backgroundLabel.setScaledContents(True)
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.calendario = QtWidgets.QCalendarWidget(Form)
        self.calendario.setGeometry(QtCore.QRect(10, 10, 781, 511))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.calendario.setFont(font)
        self.calendario.setMouseTracking(True)
        self.calendario.setStyleSheet("QCalendarWidget QWidget\n"
"{\n"
"alternate-background-color: rgb(255, 85, 0);\n"
"border: 5px solid rgb(0, 85, 255);\n"
"color: rgb(0, 85, 255)\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled\n"
"{\n"
"color: rgb(0, 85, 255);\n"
"background-color: black;\n"
"selection-background-color: rgb(255, 255, 0);\n"
"selection-color:rgb(255, 0, 255)\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar\n"
"{\n"
"background-color: rgb(255, 0, 255);\n"
"color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCalendarWidget:hover\n"
"\n"
"\n"
"\n"
"{\n"
"\n"
"\n"
"\n"
"border: 5px solid rgb(255, 0, 255);\n"
"\n"
"\n"
"\n"
"background-color: rgb(255, 85, 0);\n"
"\n"
"\n"
"\n"
"}")
        self.calendario.setGridVisible(True)
        self.calendario.setObjectName("calendario")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(820, 0, 591, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nuovaPrenotazioneButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.nuovaPrenotazioneButton.setFont(font)
        self.nuovaPrenotazioneButton.setStyleSheet("QPushButton\n"
"{\n"
"border: 5px solid rgb(0, 85, 255);\n"
"background-color: rgb(255, 0, 127);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border: 5px solid rgb(255, 0, 255);\n"
"background-color: rgb(255, 85, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"\n"
"QButton:pressed\n"
"{\n"
"border: 5px solid rgb(255, 239, 14);\n"
"background-color:rgb(255, 255, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"")
        self.nuovaPrenotazioneButton.setObjectName("nuovaPrenotazioneButton")
        self.gridLayout.addWidget(self.nuovaPrenotazioneButton, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(180, 530, 481, 351))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.clientiButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.clientiButton.setFont(font)
        self.clientiButton.setStyleSheet("QPushButton\n"
"{\n"
"border: 5px solid rgb(0, 85, 255);\n"
"background-color: rgb(255, 0, 127);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border: 5px solid rgb(255, 0, 255);\n"
"background-color: rgb(255, 85, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"\n"
"QButton:pressed\n"
"{\n"
"border: 5px solid rgb(255, 239, 14);\n"
"background-color:rgb(255, 255, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"")
        self.clientiButton.setObjectName("clientiButton")
        self.gridLayout_2.addWidget(self.clientiButton, 0, 0, 1, 1)
        self.impostazioniButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.impostazioniButton.setFont(font)
        self.impostazioniButton.setStyleSheet("QPushButton\n"
"{\n"
"border: 5px solid rgb(0, 85, 255);\n"
"background-color: rgb(255, 0, 127);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border: 5px solid rgb(255, 0, 255);\n"
"background-color: rgb(255, 85, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"\n"
"QButton:pressed\n"
"{\n"
"border: 5px solid rgb(255, 239, 14);\n"
"background-color:rgb(255, 255, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"")
        self.impostazioniButton.setObjectName("impostazioniButton")
        self.gridLayout_2.addWidget(self.impostazioniButton, 3, 0, 1, 1)
        self.dipendentiButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.dipendentiButton.setFont(font)
        self.dipendentiButton.setStyleSheet("QPushButton\n"
"{\n"
"border: 5px solid rgb(0, 85, 255);\n"
"background-color: rgb(255, 0, 127);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"border: 5px solid rgb(255, 0, 255);\n"
"background-color: rgb(255, 85, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"\n"
"QButton:pressed\n"
"{\n"
"border: 5px solid rgb(255, 239, 14);\n"
"background-color:rgb(255, 255, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"")
        self.dipendentiButton.setObjectName("dipendentiButton")
        self.gridLayout_2.addWidget(self.dipendentiButton, 1, 0, 1, 1)
        self.prenotazioniListView = QtWidgets.QListView(Form)
        self.prenotazioniListView.setGeometry(QtCore.QRect(820, 90, 591, 791))
        self.prenotazioniListView.setStyleSheet("QListView\n"
"{\n"
"border: 5px solid rgb(0, 85, 255);\n"
"background-color: rgb(255, 0, 127);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"color: rgb(0, 85, 255);\n"
"}\n"
"\n"
"QListView:hover\n"
"{\n"
"border: 5px solid rgb(255, 0, 255);\n"
"background-color: rgb(255, 85, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}\n"
"\n"
"QListView:pressed\n"
"{\n"
"border: 5px solid rgb(255, 239, 14);\n"
"background-color:rgb(255, 255, 0);\n"
"padding-left: 30px;\n"
"padding-right: 30px;\n"
"}")
        self.prenotazioniListView.setObjectName("prenotazioniListView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.clientiButton.clicked.connect(self.goToListaClienti) # LINK DEL BUTTON CLIENTI
        self.dipendentiButton.clicked.connect(self.goToListaDipendenti) #LINK BUTTON DIPENDENTI
        self.impostazioniButton.clicked.connect(self.goToImpostazioni) #LINK BUTTON IMPOSTAZIONI

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Reheasal Room Booker Home"))
        self.nuovaPrenotazioneButton.setText(_translate("Form", "Nuovo"))
        self.clientiButton.setText(_translate("Form", "Clienti"))
        self.impostazioniButton.setText(_translate("Form", "Impostazioni"))
        self.dipendentiButton.setText(_translate("Form", "Dipendenti"))

    def goToListaClienti(self):
        self.Form = QtWidgets.QMainWindow()
        self.ui = ListaClientiUi_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()
    def goToListaDipendenti(self):
        self.Form = QtWidgets.QMainWindow()
        self.ui = ListaDipendentiUi_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()
    def goToImpostazioni(self):
        self.Form = QtWidgets.QMainWindow()
        self.ui = ImpostazioniUi_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()
import Home.View.home_rc
